jobs:
      folder('Github')
      multibranchPipelineJob('Github/Jenkins') {
        branchSources {
          git {
                  id = 'configuration-as-code'
                  remote('https://github.com/Yogeshwaran-Palanisamy/jenkins.git')
              }
        }
        factory {
          workflowBranchProjectFactory {
            // Relative location within the checkout of your Pipeline script.
            scriptPath("ci/jenkinsfile")
            }
          }
        properties {
          folderLibraries {
            libraries {
              libraryConfiguration {
                name("jenkins-library")
                defaultVersion("master")
                implicit(true)
                retriever {
                  modernSCM {
                    scm {
                      git {
                        remote('https://github.com/Yogeshwaran-Palanisamy/jenkins-library.git')
                      }
                    }
                  }
                }
              }
            }
          }
        }
        orphanedItemStrategy {
          discardOldItems {
            numToKeep(30)
          }
        }
        triggers {
          periodicFolderTrigger {
            interval('5')
          }
        }
      }
