jobs:
      folder('Github') {
        displayName('Github Projects')
        properties {
          folderLibraries {
            libraries {
              libraryConfiguration {
                name("jenkins-library")
                defaultVersion("master")
                implicit(true)
                retriever {
                  modernSCM {
                    scm {
                      git {
                        remote('https://github.com/Yogeshwaran-Palanisamy/jenkins-library.git')
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      multibranchPipelineJob('Github/Jenkins') {
        branchSources {
          git {
            id = 'configuration-as-code'
            remote('https://github.com/Yogeshwaran-Palanisamy/jenkins.git')
          }
        }
        factory {
          workflowBranchProjectFactory {
            scriptPath("ci/jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath("ci/Jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath(".ci/Jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath(".ci/jenkinsfile")
          }
        }
        orphanedItemStrategy {
          discardOldItems {
            numToKeep('5')
          }
        }
        triggers {
          periodicFolderTrigger {
            interval('5')
          }
        }
      }

      multibranchPipelineJob('Github/Jenkins') {
        branchSources {
          git {
            id = 'jenkins-library'
            remote('https://github.com/Yogeshwaran-Palanisamy/jenkins-library.git')
          }
        }
        factory {
          workflowBranchProjectFactory {
            scriptPath("ci/jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath("ci/Jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath(".ci/Jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath(".ci/jenkinsfile")
          }
        }
        orphanedItemStrategy {
          discardOldItems {
            numToKeep('5')
          }
        }
        triggers {
          periodicFolderTrigger {
            interval('5')
          }
        }
      }
      multibranchPipelineJob('Github/Jenkins') {
        branchSources {
          git {
            id = 'jenkins-dsl-seed'
            remote('https://github.com/Yogeshwaran-Palanisamy/jenkin-dsl-seed.git')
          }
        }
        factory {
          workflowBranchProjectFactory {
            scriptPath("ci/jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath("ci/Jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath(".ci/Jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath(".ci/jenkinsfile")
          }
        }
        orphanedItemStrategy {
          discardOldItems {
            numToKeep('5')
          }
        }
        triggers {
          periodicFolderTrigger {
            interval('5')
          }
        }
      }
      multibranchPipelineJob('Github/Jenkins') {
        branchSources {
          git {
            id = 'configuration-as-code'
            remote('https://github.com/Yogeshwaran-Palanisamy/docker-images.git')
          }
        }
        factory {
          workflowBranchProjectFactory {
            scriptPath("ci/jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath("ci/Jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath(".ci/Jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath(".ci/jenkinsfile")
          }
        }
        orphanedItemStrategy {
          discardOldItems {
            numToKeep('5')
          }
        }
        triggers {
          periodicFolderTrigger {
            interval('5')
          }
        }
      }
