jobs:
      folder('Github') {
        displayName('Github Projects')
        properties {
          folderLibraries {
            libraries {
              libraryConfiguration {
                name("jenkins-library")
                defaultVersion("master")
                implicit(true)
                retriever {
                  modernSCM {
                    scm {
                      github {
                        repositoryUrl('https://github.com/Yogeshwaran-Palanisamy/jenkins-library.git')
                        credentialsId("continuous-integration-check")
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      multibranchPipelineJob('Github/Jenkins') {
        branchSources {
          github {
            id = 'configuration-as-code'
            repository('jenkins')
            scanCredentialsId("continuous-integration-check")
          }
        }
        factory {
          workflowBranchProjectFactory {
            scriptPath("ci/jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath("ci/Jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath(".ci/Jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath(".ci/jenkinsfile")
          }
        }
        orphanedItemStrategy {
          discardOldItems {
            numToKeep(5)
          }
        }
        triggers {
          periodicFolderTrigger {
            interval('5')
          }
        }
      }

      multibranchPipelineJob('Github/Jenkins-Library') {
        branchSources {
          github {
            id = 'jenkins-library'
            repository('jenkins-library')
            scanCredentialsId("continuous-integration-check")
          }
        }
        factory {
          workflowBranchProjectFactory {
            scriptPath("ci/jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath("ci/Jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath(".ci/Jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath(".ci/jenkinsfile")
          }
        }
        orphanedItemStrategy {
          discardOldItems {
            numToKeep(5)
          }
        }
        triggers {
          periodicFolderTrigger {
            interval('5')
          }
        }
      }
      multibranchPipelineJob('Github/Jenkins-DSL-Seed') {
        branchSources {
          github {
            id = 'jenkins-dsl-seed'
            repository('jenkins-dsl-seed')
            scanCredentialsId("continuous-integration-check")
          }
        }
        factory {
          workflowBranchProjectFactory {
            scriptPath("ci/jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath("ci/Jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath(".ci/Jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath(".ci/jenkinsfile")
          }
        }
        orphanedItemStrategy {
          discardOldItems {
            numToKeep(5)
          }
        }
        triggers {
          periodicFolderTrigger {
            interval('5')
          }
        }
      }
      multibranchPipelineJob('Github/Docker-Images') {
        branchSources {
          github {
            id = 'configuration-as-code'
            repository('docker-images')
            scanCredentialsId("continuous-integration-check")
          }
        }
        factory {
          workflowBranchProjectFactory {
            scriptPath("ci/jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath("ci/Jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath(".ci/Jenkinsfile")
          }
          workflowBranchProjectFactory {
            scriptPath(".ci/jenkinsfile")
          }
        }
        orphanedItemStrategy {
          discardOldItems {
            numToKeep(5)
          }
        }
        triggers {
          periodicFolderTrigger {
            interval('5')
          }
        }
      }
